### ISSUE TITLE
www.covsampler.net has invalid certificate

### ISSUE THREAD

**Issue by ArtPoon** [wuaipinglab/covSampler#1]
This website is blocked on Google Chrome because of an invalid certificate:
```
Common Name (CN)	www.covsampler.net
Organisation (O)	<Not part of certificate>
Organisational Unit (OU)	<Not part of certificate>
Common Name (CN)	Baidu, Inc. DV CA
Organisation (O)	Baidu, Inc.
Organisational Unit (OU)	<Not part of certificate>
Issued On	Sunday, 20 March 2022 at 20:00:00
Expires On	Saturday, 1 April 2023 at 19:59:59
```

I can bypass this in Chrome, but this is preventing other users from accessing the website.

**Comment by yexiao-cheng** [comment]
Thank you for bringing this issue to our attention. We apologize for any inconvenience this has caused and are working to resolve the issue as soon as possible.

**Comment by yexiao-cheng** [comment]
The certificate issue has been fixed.

**Comment by ArtPoon** [comment]
Fantastic, thanks!

**Comment by ArtPoon** [comment]
The certificate is expired again..

**Comment by yexiao-cheng** [comment]
Oh, sorry for the inconvenience! We'll solve it asap! Thank you for bringing this to our attention again.

**Comment by yexiao-cheng** [comment]
We've applied for another SSL certificate. The certificate problem has been solved.
